version: '3.8'
services:
  server:
    image: node:15.5.0
    command: >
      bash -c "
      cd /app
      && npm install --production
      && node index.js"
    ports:
      - $SERVER_PORT:$SERVER_PORT
    volumes:
      - ./:/app
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    ports:
      - $DB_PORT:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

volumes:
  db:
